export const QK = {
  entries: () => ['entries'] as const,
  entry: (id: string, v?: number | null) => v != null ? ['entry', id, v] as const : ['entry', id] as const,
  resources: (entryId: string) => ['resources', entryId] as const,
  comments: (entryId: string) => ['comments', entryId] as const,
    allReminders: (page?: number) => page != null ? ['reminders', 'all', page] as const : ['reminders'] as const,
    reminders: (entryId: string) => ['reminders', 'entry', entryId] as const,
    schedulePreview: (spec: string, tz: string) => ['schedule-preview', spec, tz] as const,
  refs: (entryId: string) => ['entry-refs', entryId] as const,
  history: (entryId: string) => ['entry-versions', entryId] as const,
  audit: (entryId: string) => ['entry-audit', entryId] as const,
    existingLinks: (url: string) => ['existing-links', url] as const,
  tags: () => ['tags'] as const,
  collections: () => ['collections'] as const,
  notifications: (page?: number) => page != null ? ['notifications', page] as const : ['notifications'] as const,
  resource: (entryId: string, resourceId: string) => ['resource', entryId, resourceId] as const,
  unread: () => ['notifications', 'unread'] as const,
    digest: () => ['digest'] as const,
  user: () => ['user'] as const,
  activity: (page: number) => ['activity', page] as const,
  twoFaStatus: () => ['2fa-status'] as const,
  twoFaSecret: () => ['2fa-secret'] as const,
};
